spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: root
    password: password

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

server:
  port: 5000